name: Test Summary
description: Run test results (passed, failed, skipped, ignored)

runs:
  using: "composite"
  steps:
    - name: Add executable permission to the script
      run: chmod +x ./src/main/java/scripts/summarize-test.sh 
      shell: bash

    - name: Output test results (Surefire report)
      if: always()
      run: ./src/main/java/scripts/summarize-test.sh ${{ inputs.label }}
      shell: bash
