name: Run financial website tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose your browser"
        required: true
        default: "chrome"
        type: choice
        options: [chrome, firefox, edge]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Web_sittings

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }

      - name: Run tests + generate Allure HTML
        run: |
          export URL="${{ secrets.URL }}"
          export USERNAME="${{ secrets.USERNAME }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export APP_PASSWORD="${{ secrets.APP_PASSWORD }}"
          mvn clean -Dbrowser=${{ github.event.inputs.browser }} test \
          io.qameta.allure:allure-maven:2.16.0:report

      - name: Upload Pages artifact (Allure HTML)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin   # index.html lives here
