name: Run financial website tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose your browser"
        required: true
        default: "chrome"
        type: choice
        options: [chrome, firefox, edge]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Web_sittings

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }

      - name: Run tests + generate Allure report
        run: |
          export URL="${{ secrets.URL }}"
          export USERNAME="${{ secrets.USERNAME }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export APP_PASSWORD="${{ secrets.APP_PASSWORD }}"
          mvn clean -Dbrowser=${{ github.event.inputs.browser }} test allure:report

      - name: Output test results (Surefire report)
        if: always()
        run: |
          line=$(grep -o '<testng-results[^>]*>' target/surefire-reports/testng-results.xml)
          
          # Extract numbers with grep + sed
          total=$(echo "$line" | grep -o 'total="[0-9]\+"'   | sed 's/[^0-9]//g')
          passed=$(echo "$line" | grep -o 'passed="[0-9]\+"' | sed 's/[^0-9]//g')
          failed=$(echo "$line" | grep -o 'failed="[0-9]\+"' | sed 's/[^0-9]//g')
          skipped=$(echo "$line" | grep -o 'skipped="[0-9]\+"' | sed 's/[^0-9]//g')
          ignored=$(echo "$line" | grep -o 'ignored="[0-9]\+"' | sed 's/[^0-9]//g')
          
          # Show results
          echo "### Test results summary"
          echo "- Total: $total"
          echo "- Passed: $passed"
          echo "- Failed: $failed"
          echo "- Skipped: $skipped"
          echo "- Ignored: $ignored"
                    
          FILE="target/surefire-reports/Suite/Test.html"
          if [ -f "$FILE" ]; then
          {
            echo "## Surefire: Suite/Test.html"
            echo "<details><summary>View Test.html</summary>"
            cat "$FILE"
            echo "</details>"
           } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Not found: $FILE" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload Pages artifact (Allure HTML)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin   # index.html lives here
